# Generated by Django 2.2 on 2022-03-27 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='publicmessage',
            name='pub_date',
        ),
    ]
