# Generated by Django 3.1 on 2022-09-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='time',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='content',
            field=models.TextField(default='TimeLine is Empty..'),
        ),
    ]
