# Generated by Django 3.1 on 2022-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='introduction',
            field=models.CharField(default='这是一篇文章..', max_length=100),
        ),
    ]
