# Generated by Django 2.2 on 2022-03-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20220327_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='contact_email',
        ),
    ]
